--Creación del a base de datos de Sistemas de Información
/*
ESTA TABLA SE ENCARGARA DE ALMACENAR LOS DATOS DE LOS USUARIOS QUE TENDRÁN PERMISO DE INGRESAR A LA APP
*/
CREATE TABLE user(
    Id_User INT AUTO_INCREMENT NOT NULL,
    User VARCHAR(50) NOT NULL,
    Name_User VARCHAR(50) NOT NULL,
    Password_User VARCHAR(50)NOT NULL,
    PRIMARY KEY(Id_User)
);

/*
ESTA TABLA SE ENCARGARA DE ALMACENAR LOS REQUERIMIENTO PARA EL DOCUMENTO
*/
CREATE TABLE document(
    ID_Document INT AUTO_INCREMENT NOT NULL,
    Document_Name VARCHAR(100) NOT NULL,
    Document_Target VARCHAR(50) NOT NULL,
    Area VARCHAR(50) NOT NULL,
    Subjects TEXT NOT NULL,
    Date_Document DATE NOT NULL,
    Digital_Signature VARCHAR(100) NOT NULL,
    Id_User INT NOT NULL,
    FOREIGN KEY (Id_User)REFERENCES user(Id_User)
);